spring.application.name=api-jul


spring.datasource.url=jdbc:mysql://localhost:3306/apiexample_jul?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=vaibhav@4725
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
